# Generated by Django 2.2.7 on 2020-01-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20200122_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pre_primary_performance',
            old_name='student_name',
            new_name='Student_name',
        ),
    ]
