# Generated by Django 2.2.7 on 2020-01-27 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20200124_0822'),
        ('performance', '0004_auto_20200124_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lower_primary_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English_language_activities', models.CharField(max_length=255)),
                ('Literacy_activities', models.CharField(max_length=255)),
                ('Kiswahili_language_activities', models.CharField(max_length=255)),
                ('Mathematical_activities', models.CharField(max_length=255)),
                ('Hygiene_and_nutrition_activities', models.CharField(max_length=255)),
                ('Environmental_activities', models.CharField(max_length=255)),
                ('Indigenous_language_activities', models.CharField(max_length=255)),
                ('Movement_and_creative_activities', models.CharField(max_length=255)),
                ('Religious_education_activities', models.CharField(max_length=255)),
                ('Teachers_comment', models.TextField()),
                ('Student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Pre_primary')),
            ],
        ),
    ]
