# Generated by Django 2.2.7 on 2020-01-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_upper_primary_performance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pre_primary_performance',
            old_name='Environmental_ctivities',
            new_name='Environmental_activities',
        ),
    ]
