# Generated by Django 2.2.7 on 2019-12-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=10)),
                ('student_gender', models.CharField(max_length=10)),
            ],
        ),
    ]
