# Generated by Django 2.2.7 on 2019-12-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='Student',
        ),
    ]
