# Generated by Django 2.2.7 on 2020-01-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20191226_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Pre_primary',
        ),
    ]
