# Generated by Django 2.2.7 on 2020-01-20 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200119_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lower_primary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=10)),
                ('student_gender', models.CharField(max_length=10)),
                ('parent_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
