# Generated by Django 2.2.7 on 2020-02-02 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20200128_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lower_primary',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number is invalid', regex='^\\+?1?\\d{10,12}$')]),
        ),
        migrations.AlterField(
            model_name='lower_primary',
            name='student_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only characters are allowed for Student name.', regex='[a-zA-Z.-_]')]),
        ),
        migrations.AlterField(
            model_name='pre_primary',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: Up to 10 digits allowed.', regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='pre_primary',
            name='student_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only characters are allowed for Student name.', regex='[a-zA-Z.-_]')]),
        ),
        migrations.AlterField(
            model_name='upper_primary',
            name='student_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only characters are allowed for Student name.', regex='[a-zA-Z.-_]')]),
        ),
    ]
