# Generated by Django 2.2.7 on 2020-02-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200202_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_primary',
            name='student_class',
            field=models.CharField(choices=[('One', 'Pre_primary 2'), ('Two', 'Pre_primary 1')], max_length=10),
        ),
    ]
