# Generated by Django 2.2.7 on 2020-02-02 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200202_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lower_primary',
            name='student_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only characters are allowed for Student name.', regex='[a-zA-Z]+')]),
        ),
        migrations.AlterField(
            model_name='pre_primary',
            name='student_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only characters are allowed for Student name.', regex='[a-zA-Z]+')]),
        ),
        migrations.AlterField(
            model_name='upper_primary',
            name='student_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only characters are allowed for Student name.', regex='[a-zA-Z]+')]),
        ),
    ]
